require "lib.lib"

require "script.remote-api"
require "script.layout"
require "script.electricity"
require "script.mythos-buildings"
require "script.connections.connections"
require "script.roboport.roboport"
require "script.blueprint"
require "script.camera"
require "script.overlay"
require "script.pollution"
require "script.greenhouse"
require "script.lights"
require "script.port-markers"
require "script.borehole-pump"
require "script.migration"

require "compat.factorio-maps"
require "compat.cerys"
require "compat.maraxsis"
require "compat.resource-spawner-overhaul"
require "compat.picker-dollies"
require "compat.space-exploration"

mythos.finalize_events()
