require "prototypes.hiddenEntities"
require "prototypes.collisionLayers"
require "prototypes.mythosTile"
require "prototypes.mythosEntity"
require "prototypes.virtualChest"
require "prototypes.recipe"
require "prototypes.keybinds"
require "prototypes.styles"
