data:extend({
	{
		type = "bool-setting",
		name = "mythos-no-cost",
		setting_type = "runtime-global",
		default_value = false,
		order = "a[mythos-no-cost]",
		localised_name = { "mod-setting-name.mythos-no-cost" },
		localised_description = { "mod-setting-description.mythos-no-cost" },
	},
	{
		type = "bool-setting",
		name = "mythos-no-virtual-inventory",
		setting_type = "runtime-global",
		default_value = false,
		order = "b[mythos-no-virtual-inventory]",
		localised_name = { "mod-setting-name.mythos-no-virtual-inventory" },
		localised_description = { "mod-setting-description.mythos-no-virtual-inventory" },
	},
	{
		type = "int-setting",
		name = "mythos-default-width",
		setting_type = "runtime-global",
		default_value = 20,
		minimum_value = 10,
		order = "c[mythos-default-width]",
		localised_name = { "mod-setting-name.mythos-default-width" },
		localised_description = { "mod-setting-description.mythos-default-width" },
	},
	{
		type = "int-setting",
		name = "mythos-default-height",
		setting_type = "runtime-global",
		default_value = 20,
		minimum_value = 10,
		order = "d[mythos-default-height]",
		localised_name = { "mod-setting-name.mythos-default-height" },
		localised_description = { "mod-setting-description.mythos-default-height" },
	},
})
